language: objective-c
osx_image: xcode8
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -project 'Typhoon.xcodeproj' -scheme 'Typhoon-iOSTests' -configuration Debug -destination 'OS=10.0,name=iPhone 7 Plus'  ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;

